// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FarmaceuticaBack.Models;

public partial class Contacto
{
    public int IdContacto { get; set; }

    public int IdTipoContacto { get; set; }

    public int? IdPersonal { get; set; }

    public int? IdProveedor { get; set; }

    public string IdLogistica { get; set; }

    public int? IdEstablecimiento { get; set; }

    public int? IdCliente { get; set; }

    public string Contacto1 { get; set; }

    public virtual EmpresaLogistica IdLogisticaNavigation { get; set; }

    public virtual Personal IdPersonalNavigation { get; set; }

    public virtual Proveedor IdProveedorNavigation { get; set; }

    public virtual TiposContacto IdTipoContactoNavigation { get; set; }
}