// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace FarmaceuticaBack.Models;

public partial class DetallesPedido
{
    public int IdPedido { get; set; }

    public int IdDetallePedido { get; set; }

    public int? IdMedicamentoLote { get; set; }

    public int IdProveedor { get; set; }

    public int? IdProducto { get; set; }

    public int Cantidad { get; set; }

    public decimal PrecioUnitario { get; set; }

    public virtual MedicamentosLote IdMedicamentoLoteNavigation { get; set; }

    public virtual Pedido IdPedidoNavigation { get; set; }

    public virtual Producto IdProductoNavigation { get; set; }

    public virtual Proveedor IdProveedorNavigation { get; set; }
    [JsonIgnore]
    public virtual ICollection<Inventario> Inventarios { get; set; } = new List<Inventario>();
}