// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace FarmaceuticaBack.Models;

public partial class Dispensacion
{
    public int IdFactura { get; set; }

    public int IdDispensacion { get; set; }

    public int? IdMedicamentoLote { get; set; }

    public int? IdCobertura { get; set; }

    public int? IdProducto { get; set; }

    public decimal? Descuento { get; set; }

    public decimal PrecioUnitario { get; set; }

    public int Cantidad { get; set; }

    public string Matricula { get; set; }

    public string CodigoValidacion { get; set; }

    public virtual TiposCobertura IdCoberturaNavigation { get; set; }

    public virtual Factura IdFacturaNavigation { get; set; }

    public virtual MedicamentosLote IdMedicamentoLoteNavigation { get; set; }

    public virtual Producto IdProductoNavigation { get; set; }

    [JsonIgnore]
    public virtual ICollection<Inventario> Inventarios { get; set; } = new List<Inventario>();

    public virtual Medico MatriculaNavigation { get; set; }
}