// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace FarmaceuticaBack.Models;

public partial class Factura
{
    public int IdFactura { get; set; }

    public int IdCliente { get; set; }

    public int? IdPersonalCargosEstablecimientos { get; set; }

    public DateOnly? Fecha { get; set; }
    [JsonIgnore]
    public virtual ICollection<Dispensacion> Dispensaciones { get; set; } = new List<Dispensacion>();
    [JsonIgnore]
    public virtual ICollection<FacturasTiposPago> FacturasTiposPagos { get; set; } = new List<FacturasTiposPago>();

    public virtual Cliente IdClienteNavigation { get; set; }

    public virtual PersonalCargosEstablecimiento IdPersonalCargosEstablecimientosNavigation { get; set; }
}