// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace FarmaceuticaBack.Models;

public partial class Inventario
{
    public int IdInventario { get; set; }

    public int? IdFactura { get; set; }

    public int? IdDispensacion { get; set; }

    public int? IdPedido { get; set; }

    public int? IdDetallePedido { get; set; }

    public int IdTipoMov { get; set; }

    public int IdStock { get; set; }

    public int? Cantidad { get; set; }

    public DateOnly? Fecha { get; set; }

    public virtual DetallesPedido DetallesPedido { get; set; }

    public virtual Dispensacion Dispensacione { get; set; }

    public virtual Stock IdStockNavigation { get; set; }

    public virtual TiposMovimiento IdTipoMovNavigation { get; set; }
}