// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace FarmaceuticaBack.Models;

public partial class Laboratorio
{
    public int IdLaboratorio { get; set; }

    public string NombreLaboratorio { get; set; }
    [JsonIgnore]
    public virtual ICollection<Medicamento> Medicamentos { get; set; } = new List<Medicamento>();
}