// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace FarmaceuticaBack.Models;

public partial class Marca
{
    public int IdMarca { get; set; }

    public string NombreMarca { get; set; }
    [JsonIgnore]
    public virtual ICollection<Medicamento> Medicamentos { get; set; } = new List<Medicamento>();
    [JsonIgnore]
    public virtual ICollection<Producto> Productos { get; set; } = new List<Producto>();
}