// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace FarmaceuticaBack.Models;

public partial class MedicamentosLote
{
    public int IdMedicamentoLote { get; set; }

    public int IdMedicamento { get; set; }

    public string Lote { get; set; }

    public DateOnly FechaVencimiento { get; set; }

    public bool Activo { get; set; }

    [JsonIgnore]
    public virtual ICollection<DetallesPedido> DetallesPedidos { get; set; } = new List<DetallesPedido>();
    [JsonIgnore]
    public virtual ICollection<Dispensacion> Dispensaciones { get; set; } = new List<Dispensacion>();

    public virtual Medicamento IdMedicamentoNavigation { get; set; }
    [JsonIgnore]
    public virtual ICollection<Stock> Stocks { get; set; } = new List<Stock>();
}