// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace FarmaceuticaBack.Models;

public partial class Medico
{
    public string Matricula { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public int IdTipoEspecialidad { get; set; }
    [JsonIgnore]
    public virtual ICollection<Dispensacion> Dispensaciones { get; set; } = new List<Dispensacion>();

    public virtual Especialidad IdTipoEspecialidadNavigation { get; set; }
}