// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace FarmaceuticaBack.Models;

public partial class ObraSocial
{
    public int IdObraSocial { get; set; }

    public string Nombre { get; set; }
    [JsonIgnore]
    public virtual ICollection<TiposCobertura> TiposCoberturas { get; set; } = new List<TiposCobertura>();
}