// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace FarmaceuticaBack.Models;

public partial class Pedido
{
    public int IdPedido { get; set; }

    public int IdPersonalCargosEstablecimientos { get; set; }

    public string IdLogistica { get; set; }

    public DateOnly Fecha { get; set; }
    [JsonIgnore]
    public virtual ICollection<DetallesPedido> DetallesPedidos { get; set; } = new List<DetallesPedido>();

    public virtual EmpresaLogistica IdLogisticaNavigation { get; set; }

    public virtual PersonalCargosEstablecimiento IdPersonalCargosEstablecimientosNavigation { get; set; }
}