// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace FarmaceuticaBack.Models;

public partial class Producto
{
    public int IdProducto { get; set; }

    public string Nombre { get; set; }

    public int? IdMarca { get; set; }

    public int TipoProducto { get; set; }

    public string Descripcion { get; set; }

    public decimal Precio { get; set; }

    public bool? Activo { get; set; }
    [JsonIgnore]
    public virtual ICollection<DetallesPedido> DetallesPedidos { get; set; } = new List<DetallesPedido>();
    [JsonIgnore]
    public virtual ICollection<Dispensacion> Dispensaciones { get; set; } = new List<Dispensacion>();

    public virtual Marca IdMarcaNavigation { get; set; }
    [JsonIgnore]
    public virtual ICollection<Stock> Stocks { get; set; } = new List<Stock>();

    public virtual TiposProducto TipoProductoNavigation { get; set; }
}