// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace FarmaceuticaBack.Models;

public partial class Stock
{
    public int IdStock { get; set; }

    public DateOnly Fecha { get; set; }

    public int Cantidad { get; set; }

    public int CantidadMinima { get; set; }

    public int? IdProducto { get; set; }

    public int? IdMedicamentoLote { get; set; }

    public int IdEstablecimiento { get; set; }

    public virtual Establecimiento IdEstablecimientoNavigation { get; set; }

    public virtual MedicamentosLote IdMedicamentoLoteNavigation { get; set; }

    public virtual Producto IdProductoNavigation { get; set; }
    [JsonIgnore]
    public virtual ICollection<Inventario> Inventarios { get; set; } = new List<Inventario>();
}