// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace FarmaceuticaBack.Models;

public partial class TiposDocumento
{
    public int IdTipoDoc { get; set; }

    public string TipoDocumento { get; set; }
    [JsonIgnore]
    public virtual ICollection<Cliente> Clientes { get; set; } = new List<Cliente>();
    [JsonIgnore]
    public virtual ICollection<Personal> Personals { get; set; } = new List<Personal>();
}