// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace FarmaceuticaBack.Models;

public partial class TiposCobertura
{
    public int IdTipoCobertura { get; set; }

    public int IdObraSocial { get; set; }

    public string Descripcion { get; set; }

    public decimal? Descuento { get; set; }
    [JsonIgnore]
    public virtual ICollection<Dispensacion> Dispensaciones { get; set; } = new List<Dispensacion>();

    public virtual ObraSocial IdObraSocialNavigation { get; set; }
}