// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FarmaceuticaBack.Models;

public partial class VReporteMensualObraSocial
{
    public string? ObraSocial { get; set; }

    public decimal? ImporteAReintegrar { get; set; }

    public int? Mes { get; set; }

    public int? Año { get; set; }
}