// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FarmaceuticaBack.Models;

public partial class VTotalesFacturadosVendedore
{
    public int? Año { get; set; }

    public int? Mes { get; set; }

    public int? IdPersonal { get; set; }

    public string Personal { get; set; }

    public decimal? TotalFacturado { get; set; }

    public decimal? VentaMasCara { get; set; }
}