// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FarmaceuticaBack.Models;

public partial class VTotalesFacturadosFarmacia
{
    public int IdEstablecimiento { get; set; }

    public string Establecimiento { get; set; }

    public string TotalFacturado { get; set; }

    public string MejorAñoFacturado { get; set; }
}